//
//  Resolver.swift
//  Generated by dikitgen.
//

import DIKit
import Foundation
import UIKit

extension AppResolver {

    func resolveNestedMessage() -> NestedMessage {
        return provideNestedMessage()
    }

    func resolveViewController(message: String) -> ViewController {
        let nestedMessage = resolveNestedMessage()
        return ViewController.makeInstance(dependency: .init(message: message, nested: nestedMessage))
    }

}

